name: project1
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-99.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  # 인증 관련 패키지
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  google_sign_in: ^6.2.1
 
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  pretty_dio_logger: ^1.3.1
  uuid: ^4.3.3
  kakao_flutter_sdk: ^1.9.0
  flutter_naver_login: ^1.8.0
  flutter_animate: ^4.5.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.0.0
  flutter_onboarding_slider: ^1.0.11
  permission_handler: ^11.3.0
  
  # 동영상촬영 패키지
  # camera: ^0.11.0
  camera: ^0.11.0+1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  video_player: ^2.8.6
  # cached_video_player: ^2.0.4

  visibility_detector: ^0.4.0+2
  
  preload_page_view: ^0.2.0
  marquee_widget: ^1.2.0
  simple_chips_input: ^1.2.0
  flutter_cache_manager: ^3.3.2

  
  geolocator: ^11.0.0
  flutter_svg: ^2.0.10+1
  text_scroll: ^0.2.0  

  video_compress: ^3.1.2
  hashtagable_v3: ^3.0.1
  comment_sheet: ^0.0.1
  like_button: ^2.0.5
  cached_network_image: ^3.3.1
  # video_thumbnail: ^0.5.3
  photo_gallery: ^2.2.1
  photo_manager: ^3.0.0
  extended_image: ^8.2.0
  intl: ^0.19.0
  animated_flip_counter: ^0.3.2
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  image_editor: ^1.4.0
  image: ^4.1.7
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.2.0
  flutter_native_image: ^0.0.6+1
  photo_view: ^0.15.0
  simple_progress_indicators: ^0.2.0
  scroll_to_index: ^3.0.1
  image_picker: ^1.0.7
  babstrap_settings_screen: ^0.1.6  
  chips_choice: ^3.0.1
  rxdart: ^0.27.7
  share_plus: ^8.0.3
  flutter_staggered_grid_view: ^0.7.0
  cloudflare: ^3.2.1+1
  # flutter_naver_map: ^1.2.2
  flutter_naver_map: ^1.2.2+flutter3.22
  latlong2: ^0.9.1
  xml2json: ^6.2.3
  
  http: ^1.2.1
  lottie: ^3.1.2

  functional_widget_annotation: ^0.10.0
  font_awesome_flutter: ^10.7.0
  aws_s3_upload_lite: ^0.0.8
  aws_signature_v4: ^0.5.2
  aws_common: ^0.6.4

  # Weather 관련 패키지 추가
  country_picker: ^2.0.20
  google_fonts: ^6.1.0
  material_floating_search_bar_2: ^0.5.0
  phosphor_flutter: ^2.0.1
  provider: ^6.0.5
  shimmer: ^3.0.0
  simple_animations: ^5.0.0+3
  supercharged: ^2.1.1
  #fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^25.2.6
  syncfusion_flutter_gauges: ^25.2.6
  #cached_video_player_plus: ^3.0.1
  # google_mobile_ads: ^5.1.0
  flutter_inappwebview: ^5.8.0
  google_mobile_ads: ^5.1.0
  video_player_android: ^2.4.15
  # chatting 관련 패키지
  flutter_supabase_chat_core: ^0.10.0
  flutter_login: ^5.0.0
  faker: ^2.1.0
  flutter_chat_ui: ^1.6.13
  file_picker: ^8.0.3
  file_saver: ^0.2.13
  open_filex: ^4.4.0
  timeago: ^3.6.1


  


  # better_player:
  #   git:
  #     url: 'https://github.com/Widnano/betterplayer.git'
  #     ref: 'dev/bgenidy/updatingpackagerefs'





 

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/logo/
     - assets/images/
     - assets/images/onboarding/
     - assets/images/map/
     - assets/images/weather/
     - assets/images/rain-4996916_640.jpg
     - assets/images/girl-6356393_640.jpg
     - assets/lottie/


flutter_native_splash:
  color: "#ffffff"
  image: assets/skysnap.png
  color_dark: "#121212"
  image_dark: assets/skysnap.png
  android_12:
    image: assets/skysnap.png
    icon_background_color: "#ffffff"
    image_dark: assets/skysnap.png
    icon_background_color_dark: "#121212"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
