name: project1
description: "SkySnap Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.7+27 # Ios 초기 버전
# version: 1.0.0+25  # Android 초기 버전


environment:
  sdk: ">=3.3.0-99.1.beta <4.0.0"

dependency_overrides:
  video_player_android:
    path: /Users/bumkyuchun/work/app/flutter_plugins/packages/video_player/video_player_android
  # flutter_inappwebview_android:
  #   git:
  #     url: https://github.com/holzgeist/flutter_inappwebview
  #     path: flutter_inappwebview_android
  #     ref: d89b1d32638b49dfc58c4b7c84153be0c269d057
  # flutter_inappwebview_ios:
  #   git:
  #     url: https://github.com/andychucs/flutter_inappwebview
  #     path: flutter_inappwebview_ios
  #     ref: master
  # webview_flutter_android: 3.16.1
  video_player_avfoundation:
    path: /Users/bumkyuchun/work/app/flutter_plugins/packages/video_player/video_player_avfoundation

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  # 인증 관련 패키지
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.1.3 
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  pretty_dio_logger: ^1.3.1
  uuid: ^4.3.3
  kakao_flutter_sdk: ^1.9.6
  flutter_naver_login: ^2.0.0
  flutter_local_notifications: ^17.2.1+2
  permission_handler: ^11.3.0  
  camera: ^0.11.0+1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2  
  preload_page_view: ^0.2.0
  dio_cache_interceptor: ^3.5.0
  geolocator: ^12.0.0
  flutter_svg: ^2.0.10+1
  text_scroll: ^0.2.0  
  video_compress: ^3.1.2
  hashtagable_v3: ^3.0.1
  like_button: ^2.0.5
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  image_cropper: ^8.0.2
  image_picker: ^1.0.7
  rxdart: ^0.27.7
  share_plus: ^10.0.2
  flutter_staggered_grid_view: ^0.7.0
  cloudflare: ^3.2.1+1

  flutter_naver_map: ^1.2.3+1
  latlong2: ^0.9.1
  xml2json: ^6.2.3
  http: ^1.2.1
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  animate_icons: ^2.0.0
  aws_s3_upload_lite: ^0.0.8
  aws_signature_v4: ^0.6.0
  aws_common: ^0.7.0

  # Weather 관련 패키지 추가
  # country_picker: ^2.0.20
  google_fonts: ^6.1.0
  material_floating_search_bar_2: ^0.5.0
  phosphor_flutter: ^2.0.1
  provider: ^6.0.5
  shimmer: ^3.0.0
  # supercharged: ^2.1.1
  # syncfusion_flutter_gauges: ^26.1.39
  # flutter_inappwebview: ^6.1.2
  google_mobile_ads: ^5.1.0  
  # chatting 관련 패키지
  supabase_flutter: ^2.5.6
  flutter_chat_ui: ^1.6.14
  file_picker: ^8.0.3
  file_saver: ^0.2.13
  open_filex: ^4.4.0
  timeago: ^3.6.1
  flutter_native_splash: ^2.4.0
  flutter_oss_licenses: ^3.0.2
  freezed_annotation: ^2.4.2
  json_annotation: ^4.7.0
  xml: ^6.1.0
  syncfusion_flutter_datagrid: ^26.1.40
  giffy_dialog: ^2.1.0
  app_version_update: ^5.0.3
  # flutter_dotenv: ^5.1.0
  sign_in_with_apple: ^6.1.1
  # flutter_weather_bg_null_safety: ^1.0.0
  
  video_player_android:
    path: /Users/bumkyuchun/work/app/flutter_plugins/packages/video_player/video_player_android  
  video_player_avfoundation:
    path: /Users/bumkyuchun/work/app/flutter_plugins/packages/video_player/video_player_avfoundation

  url_launcher_ios: ^6.3.1
  webview_flutter: ^4.9.0

  heif_converter: ^1.0.0
  # flutter_widget_from_html: ^0.15.2
  # flutter_quill: ^10.8.2
  # flutter_quill_extensions: ^10.8.2
  # flutter_quill_delta_from_html: ^1.4.1
  # vsc_quill_delta_to_html: ^1.0.5
  rich_text_view: ^1.3.0
  carousel_slider: ^5.0.0
  # video_editor: ^3.0.0
  # emoji_picker_flutter: ^3.1.0
  pretty_animated_text: ^2.0.0
  webviewtube: ^2.1.2
  korean_profanity_filter: ^1.0.0
  # extended_nested_scroll_view: ^6.2.1

  
  

  

    
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/login/
     - assets/images/
     - assets/images/map/
     - assets/lottie/

flutter_native_splash:
  color: "#262B49"
  image:  assets/skysnap1.png
  android_12:
    image:   assets/skysnap1.png
   # color: "#262B49"
    # icon_background_color: "#262B49"
    image_dark:   assets/skysnap1.png
  #  color_dark: "#262B49"
    # icon_background_color_dark: "#262B49"

  fullscreen: true
  android: true
  ios: true
  web: false
 

  # android_gravity: center
  # ios_content_mode: center
  # web_image_mode: center

  # android_screen_orientation: portrait

  info_plist_files:
    - 'ios/Runner/Info.plist'

  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
