name: project1
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0-99.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  # 인증 관련 패키지
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  google_sign_in: ^6.2.1
 
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  pretty_dio_logger: ^1.3.1
  uuid: ^4.3.3
  kakao_flutter_sdk: ^1.9.0
  flutter_naver_login: ^1.8.0
  flutter_animate: ^4.5.0
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^17.0.0
  flutter_onboarding_slider: ^1.0.11
  permission_handler: ^11.3.0
  story_view: ^0.16.5
  # 동영상촬영 패키지
  camera: ^0.10.5+9
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  video_player: ^2.8.3
  visibility_detector: ^0.4.0+2
  
  preload_page_view: ^0.2.0
  marquee_widget: ^1.2.0
  simple_chips_input: ^1.2.0
  flutter_cache_manager: ^3.3.1
  cached_video_player_plus: ^2.0.0
  geolocator: ^11.0.0
  flutter_svg: ^2.0.10+1
  text_scroll: ^0.2.0


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/logo/
     - assets/images/
     - assets/images/onboarding/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
