// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm3pLtoijj6Xuiytt9R1-dQXtL6cybRaw',
    appId: '1:498191521998:web:dc3507364283253660189f',
    messagingSenderId: '498191521998',
    projectId: 'project1-c07d1',
    authDomain: 'project1-c07d1.firebaseapp.com',
    storageBucket: 'project1-c07d1.appspot.com',
    measurementId: 'G-3H65PVPYGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgEZ4xNo5WXYthA1l8y9XLK118y6gbTpg',
    appId: '1:498191521998:android:002996e3f3908e5860189f',
    messagingSenderId: '498191521998',
    projectId: 'project1-c07d1',
    storageBucket: 'project1-c07d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbWO9qyHrCi7gNiYKCBxZG1_P6HSsRTo',
    appId: '1:498191521998:ios:12e171cd28277f1560189f',
    messagingSenderId: '498191521998',
    projectId: 'project1-c07d1',
    storageBucket: 'project1-c07d1.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJbWO9qyHrCi7gNiYKCBxZG1_P6HSsRTo',
    appId: '1:498191521998:ios:14e2be6ddd34ce1e60189f',
    messagingSenderId: '498191521998',
    projectId: 'project1-c07d1',
    storageBucket: 'project1-c07d1.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
